project/SSBU/Characters/urls.py
from django.urls import path

from . import views

app_name = "characters"

urlpatterns = [
   path("", views.index, name="index"),
   path("cookies", views.cookies, name="cookies"),
   path("djangoforms", views.djangoforms, name="djangoforms"),
   path("nondjangoforms", views.nondjangoforms, name="nondjangoforms"),   
   path("character_info", views.character_info, name="character_info"),
   path("search", views.search, name="search"),
   path("searched",views.searched, name="searched"),
]

project/SSBU/SSBU/urls.py
from django.contrib import admin
from django.urls import path

from django.urls import path, include

urlpatterns = [
   path('admin/', admin.site.urls),
   path('Characters/', include('Characters.urls', namespace='Characters')),
] 

project/SSBU/Characters/models.py
from django.db import models

# Create your models here.

project/SSBU/Characters/views.py
from django.shortcuts import render
from .Character_forms import CharacterForm
from django.shortcuts import render, redirect
from django.contrib import messages
from django.http import JsonResponse


import datetime
import json
character_list = [
    {
        'Mario': {
            'name': 'Mario',
            'height': "5'1\" (155 cm)",
            'weight': 'Plumber-weight',
            'series': 'Super Mario',
            'image': '/images/150px-Mario_SSBU.png'
        }
    },
    {
        'Donkey Kong': {
            'name': 'Donkey Kong',
            'height': "7'0\" (213 cm)",
            'weight': 'Heavyweight',
            'series': 'Donkey Kong',
            'image': '/images/150px-Donkey_Kong_SSBU.png'
        }
    },
    {
        'Link': {
            'name': 'Link',
            'height': "5'7\" (170 cm)",
            'weight': 'Heroic weight',
            'series': 'The Legend of Zelda',
            'image': '/images/150px-Link_SSBU.png'
        }
    },
    {
        'Samus': {
            'name': 'Samus Aran',
            'height': "6'3\" (190 cm)",
            'weight': 'Power Suit weight',
            'series': 'Metroid',
            'image': '/images/150px-Samus_SSBU.png'
        }
    },
    {
        'Dark Samus': {
            'name': 'Dark Samus',
            'height': "6'4\" (193 cm)",
            'weight': 'Phazon weight',
            'series': 'Metroid',
            'image': '/images/150px-Dark_Samus_SSBU.jpeg'
        }
    },
    {
        'Yoshi': {
            'name': 'Yoshi',
            'height': "3'7\" (109 cm)",
            'weight': 'Lightweight',
            'series': 'Super Mario',
            'image': '/images/150px-Yoshi_SSBU.png'
        }
    },
    {
        'Kirby': {
            'name': 'Kirby',
            'height': "8\" (20 cm)",
            'weight': 'Lightweight',
            'series': 'Kirby',
            'image': '/images/150px-Kirby_SSBU.png'
        }
    },
    {
        'Fox': {
            'name': 'Fox McCloud',
            'height': "5'8\" (173 cm)",
            'weight': 'Middleweight',
            'series': 'Star Fox',
            'image': '/images/150px-Fox_SSBU.png'
        }
    },
    {
        'Pikachu': {
            'name': 'Pikachu',
            'height': "1'4\" (40 cm)",
            'weight': 'Featherweight',
            'series': 'Pokémon',
            'image': '/images/150px-Pikachu_SSBU.png'
        }
    },
    {
        'Luigi': {
            'name': 'Luigi',
            'height': "5'9\" (175 cm)",
            'weight': 'Plumber-weight',
            'series': 'Super Mario',
            'image': '/images/137px-Luigi_SSBU.png'
        }
    },
    {
        'Ness': {
            'name': 'Ness',
            'height': "4'11\" (150 cm)",
            'weight': 'Kid-weight',
            'series': 'EarthBound',
            'image': '/images/150px-Ness_SSBU.png'
        }
    },
    {
        'Captain Falcon': {
            'name': 'Captain Falcon',
            'height': "6'2\" (188 cm)",
            'weight': 'Middleweight',
            'series': 'F-Zero',
            'image': '/images/150px-Captain_Falcon_SSBU.png'
        }
    },
    {
        'Jigglypuff': {
            'name': 'Jigglypuff',
            'height': "1'8\" (51 cm)",
            'weight': 'Balloon-weight',
            'series': 'Pokémon',
            'image': '/images/150px-Jigglypuff_SSBU.png'
        }
    },
    {
        'Peach': {
            'name': 'Princess Peach',
            'height': "6'0\" (183 cm)",
            'weight': 'Lightweight',
            'series': 'Super Mario',
            'image': '/images/133px-Peach_SSBU.png'
        }
    },
    {
        'Daisy': {
            'name': 'Princess Daisy',
            'height': "5'11\" (180 cm)",
            'weight': 'Lightweight',
            'series': 'Super Mario',
            'image': '/images/150px-Princess_Daisy_SSBU.jpeg'
        }
    },
    {
        'Bowser': {
            'name': 'Bowser',
            'height': "8'7\" (261 cm)",
            'weight': 'Super Heavyweight',
            'series': 'Super Mario',
            'image': '/images/150px-Bowser_SSBU.png'
        }
    },
    {
        'Ice Climbers': {
            'name': 'Ice Climbers',
            'height': "3'5\" (104 cm)",
            'weight': 'Middleweight',
            'series': 'Ice Climber',
            'image': '/images/150px-Ice_Climbers_SSBU.png'
        }
    },
    {
        'Sheik': {
            'name': 'Sheik',
            'height': "5'10\" (178 cm)",
            'weight': 'Middleweight',
            'series': 'The Legend of Zelda',
            'image': '/images/150px-Sheik_SSBU.png'
        }
    },
    {
        'Zelda': {
            'name': 'Princess Zelda',
            'height': "5'7\" (170 cm)",
            'weight': 'Middleweight',
            'series': 'The Legend of Zelda',
            'image': '/images/150px-Zelda_SSBU.png'
        }
    },
    {
        'Dr. Mario': {
            'name': 'Dr. Mario',
            'height': "5'7\" (170 cm)",
            'weight': 'Middleweight',
            'series': 'Super Mario',
            'image': '/images/150px-Dr.png'
        }
    },
    {
        'Pichu': {
            'name': 'Pichu',
            'height': "1'0\" (30 cm)",
            'weight': 'Lightweight',
            'series': 'Pokémon',
            'image': '/images/150px-Pichu_SSBU.png'
        }
    },
    {
        'Falco': {
            'name': 'Falco Lombardi',
            'height': "6'2\" (188 cm)",
            'weight': 'Featherweight',
            'series': 'Star Fox',
            'image': '/images/150px-Falco_SSBU.png'
        }
    },
    {
        'Marth': {
            'name': 'Marth',
            'height': "6'0\" (183 cm)",
            'weight': 'Middleweight',
            'series': 'Fire Emblem',
            'image': '/images/150px-Marth_SSBU.png'
        }
    },
    {
        'Lucina': {
            'name': 'Lucina',
            'height': "5'7\" (170 cm)",
            'weight': 'Middleweight',
            'series': 'Fire Emblem',
            'image': '/images/150px-Lucina_SSBU.png'
        }
    },
    {
        'Young Link': {
            'name': 'Young Link',
            'height': "5'6\" (168 cm)",
            'weight': 'Middleweight',
            'series': 'The Legend of Zelda',
            'image': '/images/150px-Young_Link_SSBU.png'
        }
    },
    {
        'Ganondorf': {
            'name': 'Ganondorf',
            'height': "7'6\" (229 cm)",
            'weight': 'Super Heavyweight',
            'series': 'The Legend of Zelda',
            'image': '/images/149px-Ganondorf_SSBU.png'
        }
    },
    {
        'Mewtwo': {
            'name': 'Mewtwo',
            'height': "6'7\" (201 cm)",
            'weight': 'Middleweight',
            'series': 'Pokémon',
            'image': '/images/149px-Mewtwo_SSBU.png'
        }
    },
    {
        'Roy': {
            'name': 'Roy',
            'height': "5'8\" (173 cm)",
            'weight': 'Middleweight',
            'series': 'Fire Emblem',
            'image': '/images/150px-Roy_SSBU.png'
        }
    },
    {
        'Chrom': {
            'name': 'Chrom',
            'height': "6'0\" (183 cm)",
            'weight': 'Middleweight',
            'series': 'Fire Emblem',
            'image': '/images/150px-Chrom_SSBU.jpeg'
        }
    },
    {
        'Mr. Game & Watch': {
            'name': 'Mr. Game & Watch',
            'height': "2D (Variable height)",
            'weight': 'Variable weight',
            'series': 'Game & Watch',
            'image': '/images/150px-Mr.png'
        }
    },
    {
        'Meta Knight': {
            'name': 'Meta Knight',
            'height': "6'5\" (196 cm)",
            'weight': 'Middleweight',
            'series': 'Kirby',
            'image': '/images/150px-Kirby_SSBU.png'
        }
    },
    {
        'Pit': {
            'name': 'Pit',
            'height': "5'2\" (157 cm)",
            'weight': 'Middleweight',
            'series': 'Kid Icarus',
            'image': '/images/150px-Pit_SSBU.png'
        }
    },
    {
        'Dark Pit': {
            'name': 'Dark Pit',
            'height': "6'0\" (183 cm)",
            'weight': 'Middleweight',
            'series': 'Kid Icarus',
            'image': '/images/142px-Dark_Pit_SSBU.png'
        }
    },
    {
        'Zero Suit Samus': {
            'name': 'Zero Suit Samus',
            'height': "5'9\" (175 cm)",
            'weight': 'Middleweight',
            'series': 'Metroid',
            'image': '/images/150px-Zero_Suit_Samus_SSBU.png'
        }
    },
    {
        'Wario': {
            'name': 'Wario',
            'height': "5'7\" (170 cm)",
            'weight': 'Middleweight',
            'series': 'Super Mario',
            'image': '/images/150px-Wario_SSBU.png'
        }
    },
    {
        'Snake': {
            'name': 'Solid Snake',
            'height': "6'0\" (183 cm)",
            'weight': 'Middleweight',
            'series': 'Metal Gear',
            'image': 'images/123px-Snake_SSBU.png'
        }
    },
    {
        'Ike': {
            'name': 'Ike',
            'height': "6'4\" (193 cm)",
            'weight': 'Heavyweight',
            'series': 'Fire Emblem',
            'image': '/images/150px-Ike_SSBU.png'
        }
    },
    {
        'Pokemon Trainer': {
            'name': 'Pokémon Trainer',
            'height': "5'3\" (160 cm) (Average of the three Pokémon)",
            'weight': 'Variable weight (Depends on the active Pokémon)',
            'series': 'Pokémon',
            'image': '/images/150px-Charizard_SSBU.png'
        }
    },
    {
        'Diddy Kong': {
            'name': 'Diddy Kong',
            'height': "3'0\" (91 cm)",
            'weight': 'Featherweight',
            'series': 'Donkey Kong',
            'image': '/images/145px-Diddy_Kong_SSBU.png'
        }
    },
    {
        'Lucas': {
            'name': 'Lucas',
            'height': "4'3\" (130 cm)",

project/SSBU/Characters/templates/Characters/character_info.html
{% extends "base.html" %}

{% block content %}
{% load static %}

<h1>List of Characters</h1>
<table class="character-table">
    <thead>
        <tr>
            <th>Creade - Django</th>
            <th>Create - Non-Django</th>
        </tr>
    </thead>
    <tbody>
        <td>
            <form action="{% url 'Characters:character_info' %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="i1" value=True>
                <button type="submit">Create</button>
            </form>
        </td>
        <td>
            <form action="{% url 'Characters:character_info' %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="i2" value=True>
                <button type="submit">Create</button>
            </form>
        </td>
    </tbody>
</table>
<table class="character-table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Height</th>
            <th>Weight</th>
            <th>Series</th>
            <th>Image</th>
            <th>Download</th> <!-- Add a new column for the download button -->
            <th>Delete</th>
            <th>Edit</th>
        </tr>
    </thead>
    <tbody>
        {% for character_dict in character_list %}
            {% for character_name, character_attributes in character_dict.items %}
                <tr>
                    <td>{{ character_attributes.name }}</td>
                    <td>{{ character_attributes.height }}</td>
                    <td>{{ character_attributes.weight }}</td>
                    <td>{{ character_attributes.series }}</td>
                    <td><img src="{% static character_attributes.image %}" alt="Character Image"></td>
                    <td>
                        <a href="{% static character_attributes.image %}" download>
                            <button>Download</button>
                        </a>
                    </td>
                    <td>
                        <form action="{% url 'Characters:character_info' %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="item_to_delete" value="{{ character_name }}">
                            <button type="submit">Delete</button>
                        </form>
                    </td>
                    <td>
                        <form action="{% url 'Characters:character_info' %}" method="post">
                            {% csrf_token %}
                            <input type="hidden" name="data" value="{{ character_name }}">
                            <button type="submit">Edit</button>
                        </form>
                    </td>
                </tr>
            {% endfor %}
        {% endfor %}
    </tbody>
</table>
{% endblock content %}

project/SSBU/Characters/templates/Characters/cookies.html
{% extends "base.html" %}

{% block content %}

<h3>
This website was made by Jonathan Yap, John Chandler III, Tejas Siddaramaiah, and Jason Lei
</h3>
<br>

You have visited and reloaded this page: 
{{visit_nbr}}
 times

{% endblock content %}

project/SSBU/Characters/templates/Characters/djangoforms.html
{% extends "base.html" %}

{% block content %}
   <form action="{% url 'Characters:djangoforms' %}" method="post">
       {% csrf_token %}
       <label for="action">Action: </label>
       <select name="action" required>
           <option value="edit">Edit</option>
           <option value="create"{% if select %}selected{% endif %}>Create</option>
       </select>
       <br>
       {{ character_form.Characters.label_tag }}
       {{ character_form.Characters }}
       <br>
       {{ character_form.name.label_tag }}
       {{ character_form.name }}
       <br>
       {{ character_form.height.label_tag }}
       {{ character_form.height }}
       <br>
       {{ character_form.weight.label_tag }}
       {{ character_form.weight }}
       <br>
       {{ character_form.series.label_tag }}
       {{ character_form.series }}
       <br>
       <input type="submit" value="Submit">
   </form>
   {% if messages %}
    <div class="messages">
        {% for message in messages %}
        <div{% if message.tags %} class="{{ message.tags }}"{% endif %}>
            {{ message }}
        </div>
        {% endfor %}
    </div>
    {% endif %}
{% endblock content %}

project/SSBU/Characters/templates/Characters/index.html
{% extends "base.html" %}
{% block content %}
<h1>Welcome to SSBU!</h1>
This website shows all the Super Smash Bros Ultimate (SSBU) characters as of 2023. There is a navbar on top of the website where you can navigate between editing/deleting a character using a Django form, editing/deleting a character without a Django form, seeing the list view of characters, and searching for a specific character.
<br><br>
We hope you enjoy! 

{% endblock content %}

project/SSBU/Characters/templates/Characters/nondjangoforms.html
{% load static %}
<head>
   <link rel="stylesheet" href="{% static 'main.css' %}">
</head>
{% block content %}
<div id="navigation">
    <div id="nav_div">
        <a href="search" class="{% if request.resolver_match.url_name == 'search' %}active{% endif %}">Search<br></a>
        <a href="nondjangoforms" class="{% if request.resolver_match.url_name == 'nondjangoforms' %}active{% endif %}">Non-Django Form<br></a>
        <a href="djangoforms" class="{% if request.resolver_match.url_name == 'djangoforms' %}active{% endif %}">Django Form <br></a>
        <a href="character_info" class="{% if request.resolver_match.url_name == 'character_info' %}active{% endif %}">Character Info<br></a>
        <a href="cookies" class="{% if request.resolver_match.url_name == 'cookies' %}active{% endif %}">Cookies<br></a>
    </div>
 </div>
 <br><br><br><br>
<form action="{% url 'Characters:nondjangoforms' %}" method="post">
    {% csrf_token %}
    <label for="action">Action:</label>
    <select name="action" required>
        <option value="edit">Edit</option>
        <option value="create"{% if select %}selected{% endif %}>Create</option>
    </select>
    <br>
    <label for="Characters">Characters:</label>
    <select name="Characters" required>
        {% for character_dict in character_list %}
            {% for character_name, character_data in character_dict.items %}
                <option value="{{ character_name }}"{% if character_name == initial_data.name %}selected{% endif %}>{{ character_name }}</option>
            {% endfor %}
        {% endfor %}
    </select>
    <br>
    <label for="name">Name:</label>
    <input type="text" name="name" value="{{initial_data.name}}"required>
    <br>
    <label for="height">Height:</label>
    <input type="text" name="height" value="{{ initial_data.height }}"required>
    <br>
    <label for="weight">Weight:</label>
    <input type="text" name="weight" value="{{ initial_data.weight }}"required>
    <br>
    <label for="series">Series:</label>
    <input type="text" name="series" value="{{ initial_data.series }}"required>
    <br>
    <input type="submit" value="Submit">
</form>
{% if messages %}
<div class="messages">
    {% for message in messages %}
    <div{% if message.tags %} class="{{ message.tags }}"{% endif %}>
        {{ message }}
    </div>
    {% endfor %}
</div>
{% endif %}
{% endblock content %}

project/SSBU/Characters/templates/Characters/search.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Search Character</title>
    <link rel="stylesheet" href="{% static 'main.css' %}">
</head>

<body>
    <div id="navigation">
        <div id="nav_div">
            <a href="search" class="{% if request.resolver_match.url_name == 'search' %}active{% endif %}">Search<br></a>
            <a href="nondjangoforms" class="{% if request.resolver_match.url_name == 'nondjangoforms' %}active{% endif %}">Non-Django Form<br></a>
            <a href="djangoforms" class="{% if request.resolver_match.url_name == 'djangoforms' %}active{% endif %}">Django Form <br></a>
            <a href="character_info" class="{% if request.resolver_match.url_name == 'character_info' %}active{% endif %}">Character Info<br></a>
            <a href="cookies" class="{% if request.resolver_match.url_name == 'cookies' %}active{% endif %}">Cookies<br></a>
        </div>
     </div>
     <br><br><br><br>
    <h1>Search Character</h1>

    <form method="post" action="{% url 'Characters:search' %}">
        {% csrf_token %}
        <label for="character-name">Enter Character Name:</label>
        <input type="text" id="character-name" name="selected_character" required>
        <button type="submit">Search</button>
    </form>
</body>

</html>

project/SSBU/Characters/templates/Characters/searched.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Searched Character Information</title>
   <link rel="stylesheet" href="{% static 'main.css' %}">
</head>

<body>
    <h1>Character Information</h1>
    {% load static %}
    <div id="navigation">
        <div id="nav_div">
            <a href="search" class="{% if request.resolver_match.url_name == 'search' %}active{% endif %}">Search<br></a>
            <a href="nondjangoforms" class="{% if request.resolver_match.url_name == 'nondjangoforms' %}active{% endif %}">Non-Django Form<br></a>
            <a href="djangoforms" class="{% if request.resolver_match.url_name == 'djangoforms' %}active{% endif %}">Django Form <br></a>
            <a href="character_info" class="{% if request.resolver_match.url_name == 'character_info' %}active{% endif %}">Character Info<br></a>
            <a href="cookies" class="{% if request.resolver_match.url_name == 'cookies' %}active{% endif %}">Cookies<br></a>
        </div>
     </div>
     <br>

    {% if selected_characters %}
    {%for selected_character in selected_characters%}
    <h2>Name: {{ selected_character.name }}</h2>
    <p>Height: {{ selected_character.height }}</p>
    <p>Weight: {{ selected_character.weight }}</p>
    <p>Series: {{ selected_character.series }}</p>
    <!-- Add more character attributes here as needed -->
    <img src="{% static selected_character.image%}" alt = "my image"> </img>
    {%endfor%}
    {% else %}
    <p>No information available for the selected character.</p>
    {% endif %}
    <br>
    <a href="{% url 'Characters:search' %}">Search Again</a>
</body>

</html>